In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv('moviesdata.csv')
movies.head()

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811

In [3]:
movies.shape

(10000, 9)

In [4]:
movies.describe

<bound method NDFrame.describe of           id                                          title  \
0        278                       The Shawshank Redemption
1      19404                    Dilwale Dulhania Le Jayenge
2        238                                  The Godfather
3        424                               Schindler's List
4        240                         The Godfather: Part II
...      ...                                            ...
9995   10196                             The Last Airbender
9996  331446                       Sharknado 3: Oh Hell No!
9997   13995                                Captain America
9998    2312  In the Name of the King: A Dungeon Siege Tale
9999  455957                                         Domino

                                                 genre original_language  \
0                                          Drama,Crime                en
1                                 Comedy,Drama,Romance                hi
2                                          Drama,Crime                en
3                                    Drama,History,War                en
4                                          Drama,Crime                en
...                                                ...               ...
9995                          Action,Adventure,Fantasy                en
9996  Action,TV Movie,Science Fiction,Comedy,Adventure                en
9997                        Action,Science Fiction,War                en
9998                    Adventure,Fantasy,Action,Drama                en
9999                             Thriller,Action,Crime                en

                                               overview  popularity  \
0     Framed in the 1940s for the double murder of h...      94.075
1     Raj is a rich, carefree, happy-go-lucky second...      25.408
2     Spanning the years 1945 to 1955, a chronicle o...      90.585
3     The true story of how businessman Oskar Schind...      44.761
4     In the continuing saga of the Corleone crime f...      57.749
...                                                 ...         ...
9995  The story follows the adventures of Aang, a yo...      98.322
9996  The sharks take bite out of the East Coast whe...      12.490
9997  During World War II, a brave, patriotic Americ...      18.333
9998  A man named Farmer sets out to rescue his kidn...      15.159
9999  Seeking justice for his partner’s murder by an...      16.482

     release_date  vote_average  vote_count
0      1994-09-23           8.7       21862
1      1995-10-19           8.7        3731
2      1972-03-14           8.7       16280
3      1993-12-15           8.6       12959
4      1974-12-20           8.6        9811
...           ...           ...         ...
9995   2010-06-30           4.7        3347
9996   2015-07-22           4.7         417
9997   1990-12-14           4.6         332
9998   2007-11-29           4.7         668
9999   2019-05-31           4.6         221

[10000 rows x 9 columns]>

In [5]:
movies.info

<bound method DataFrame.info of           id                                          title  \
0        278                       The Shawshank Redemption
1      19404                    Dilwale Dulhania Le Jayenge
2        238                                  The Godfather
3        424                               Schindler's List
4        240                         The Godfather: Part II
...      ...                                            ...
9995   10196                             The Last Airbender
9996  331446                       Sharknado 3: Oh Hell No!
9997   13995                                Captain America
9998    2312  In the Name of the King: A Dungeon Siege Tale
9999  455957                                         Domino

                                                 genre original_language  \
0                                          Drama,Crime                en
1                                 Comedy,Drama,Romance                hi
2                                          Drama,Crime                en
3                                    Drama,History,War                en
4                                          Drama,Crime                en
...                                                ...               ...
9995                          Action,Adventure,Fantasy                en
9996  Action,TV Movie,Science Fiction,Comedy,Adventure                en
9997                        Action,Science Fiction,War                en
9998                    Adventure,Fantasy,Action,Drama                en
9999                             Thriller,Action,Crime                en

                                               overview  popularity  \
0     Framed in the 1940s for the double murder of h...      94.075
1     Raj is a rich, carefree, happy-go-lucky second...      25.408
2     Spanning the years 1945 to 1955, a chronicle o...      90.585
3     The true story of how businessman Oskar Schind...      44.761
4     In the continuing saga of the Corleone crime f...      57.749
...                                                 ...         ...
9995  The story follows the adventures of Aang, a yo...      98.322
9996  The sharks take bite out of the East Coast whe...      12.490
9997  During World War II, a brave, patriotic Americ...      18.333
9998  A man named Farmer sets out to rescue his kidn...      15.159
9999  Seeking justice for his partner’s murder by an...      16.482

     release_date  vote_average  vote_count
0      1994-09-23           8.7       21862
1      1995-10-19           8.7        3731
2      1972-03-14           8.7       16280
3      1993-12-15           8.6       12959
4      1974-12-20           8.6        9811
...           ...           ...         ...
9995   2010-06-30           4.7        3347
9996   2015-07-22           4.7         417
9997   1990-12-14           4.6         332
9998   2007-11-29           4.7         668
9999   2019-05-31           4.6         221

[10000 rows x 9 columns]>

In [6]:
movies.isnull().sum()

id                    0
title                 0
genre                 3
original_language     0
overview             13
popularity            0
release_date          0
vote_average          0
vote_count            0
dtype: int64

In [7]:
movies.columns

Index(['id', 'title', 'genre', 'original_language', 'overview', 'popularity',
       'release_date', 'vote_average', 'vote_count'],
      dtype='object')

In [8]:
movies['tag'] = movies['overview'] + movies['genre']
movies

,id,title,genre,original_language,overview,popularity,release_date,vote_average,vote_count,tag
0,278,The Shawshank Redemption,"Drama,Crime",en,Framed in the 1940s for the double murder of h...,94.075,1994-09-23,8.7,21862,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,"Comedy,Drama,Romance",hi,"Raj is a rich, carefree, happy-go-lucky second...",25.408,1995-10-19,8.7,3731,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,"Drama,Crime",en,"Spanning the years 1945 to 1955, a chronicle o...",90.585,1972-03-14,8.7,16280,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,"Drama,History,War",en,The true story of how businessman Oskar Schind...,44.761,1993-12-15,8.6,12959,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,"Drama,Crime",en,In the continuing saga of the Corleone crime f...,57.749,1974-12-20,8.6,9811,In the continuing saga of the Corleone crime f...
...,...,...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,"Action,Adventure,Fantasy",en,"The story follows the adventures of Aang, a yo...",98.322,2010-06-30,4.7,3347,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,"Action,TV Movie,Science Fiction,Comedy,Adventure",en,The sharks take bite out of the East Coast whe...,12.490,2015-07-22,4.7,417,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,"Action,Science Fiction,War",en,"During World War II, a brave, patriotic Americ...",18.333,1990-12-14,4.6,332,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,"Adventure,Fantasy,Action,Drama",en,A man named Farmer sets out to rescue his kidn...,15.159,2007-11-29,4.7,668,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,"Thriller,Action,Crime",en,Seeking justice for his partner’s murder by an...,16.482,2019-05-31,4.6,221,Seeking justice for his partner’s murder by an...

In [9]:
movies1 = movies.drop(columns= ['genre','overview'])
movies1.head()

,id,title,original_language,popularity,release_date,vote_average,vote_count,tag
0,278,The Shawshank Redemption,en,94.075,1994-09-23,8.7,21862,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,hi,25.408,1995-10-19,8.7,3731,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,en,90.585,1972-03-14,8.7,16280,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,en,44.761,1993-12-15,8.6,12959,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,en,57.749,1974-12-20,8.6,9811,In the continuing saga of the Corleone crime f...

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

In [11]:
cv = CountVectorizer(max_features=10000 , stop_words='english')
cv

CountVectorizer(max_features=10000, stop_words='english')

In [12]:
vector=cv.fit_transform(movies1['tag'].values.astype('U')).toarray()
vector.shape

(10000, 10000)

In [13]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)

In [14]:
similarity

array([[1.        , 0.05634362, 0.12888482, ..., 0.07559289, 0.11065667,
        0.06388766],
       [0.05634362, 1.        , 0.07624929, ..., 0.        , 0.03636965,
        0.        ],
       [0.12888482, 0.07624929, 1.        , ..., 0.02273314, 0.06655583,
        0.08645856],
       ...,
       [0.07559289, 0.        , 0.02273314, ..., 1.        , 0.03253   ,
        0.02817181],
       [0.11065667, 0.03636965, 0.06655583, ..., 0.03253   , 1.        ,
        0.0412393 ],
       [0.06388766, 0.        , 0.08645856, ..., 0.02817181, 0.0412393 ,
        1.        ]])

In [15]:
movies1[movies1['title']=="The Godfather"].index[0]

np.int64(2)

In [16]:
distance = sorted(list(enumerate(similarity[5])), reverse=True, key=lambda vector:vector[1])
# for i in distance[0:5]:
#     print(movies1.iloc[i[0]].title)

distance1 = sorted(list(enumerate(similarity[5])), reverse=True, key= lambda vector: vector[1] )
distance1

[(5, np.float64(1.0)),
 (7646, np.float64(0.47434164902525694)),
 (4299, np.float64(0.39528470752104744)),
 (2990, np.float64(0.36084391824351614)),
 (3369, np.float64(0.3273268353539886)),
 (9794, np.float64(0.3198010745334156)),
 (9641, np.float64(0.31622776601683794)),
 (5692, np.float64(0.31277162108561213)),
 (5782, np.float64(0.3125)),
 (5834, np.float64(0.3125)),
 (3473, np.float64(0.30316953129541624)),
 (3842, np.float64(0.30316953129541624)),
 (7471, np.float64(0.30316953129541624)),
 (6546, np.float64(0.30151134457776363)),
 (6140, np.float64(0.2886751345948129)),
 (6672, np.float64(0.2886751345948129)),
 (1542, np.float64(0.2795084971874737)),
 (6995, np.float64(0.2785430072655778)),
 (6278, np.float64(0.2773500981126146)),
 (8503, np.float64(0.2727723627949905)),
 (3292, np.float64(0.26967994498529685)),
 (9701, np.float64(0.26940795304016235)),
 (479, np.float64(0.2672612419124244)),
 (5015, np.float64(0.2672612419124244)),
 (5923, np.float64(0.2672612419124244)),
 (7450, np.float64(0.2672612419124244)),
 (2959, np.float64(0.266500895444513)),
 (3413, np.float64(0.266500895444513)),
 (5472, np.float64(0.266500895444513)),
 (645, np.float64(0.2651650429449553)),
 (8167, np.float64(0.2651650429449553)),
 (703, np.float64(0.26064301757134345)),
 (1952, np.float64(0.26064301757134345)),
 (2133, np.float64(0.2581988897471611)),
 (2448, np.float64(0.2581988897471611)),
 (7895, np.float64(0.2581988897471611)),
 (8209, np.float64(0.2581988897471611)),
 (6006, np.float64(0.25802342327107)),
 (1874, np.float64(0.2551551815399144)),
 (1559, np.float64(0.253546276418555)),
 (1271, np.float64(0.25)),
 (2719, np.float64(0.25)),
 (3261, np.float64(0.25)),
 (4451, np.float64(0.25)),
 (6683, np.float64(0.25)),
 (7447, np.float64(0.25)),
 (8950, np.float64(0.25)),
 (8651, np.float64(0.24514516892273006)),
 (4273, np.float64(0.24333213169614382)),
 (553, np.float64(0.24253562503633297)),
 (1247, np.float64(0.24253562503633297)),
 (2500, np.float64(0.24253562503633297)),
 (2952, np.float64(0.24253562503633297)),
 (2969, np.float64(0.24253562503633297)),
 (7095, np.float64(0.24253562503633297)),
 (7135, np.float64(0.24253562503633297)),
 (7519, np.float64(0.24253562503633297)),
 (9862, np.float64(0.24253562503633297)),
 (9822, np.float64(0.2405626121623441)),
 (3906, np.float64(0.24038098691020582)),
 (3060, np.float64(0.23717082451262844)),
 (3132, np.float64(0.23717082451262844)),
 (4330, np.float64(0.23717082451262844)),
 (8289, np.float64(0.23717082451262844)),
 (2330, np.float64(0.23570226039551587)),
 (3602, np.float64(0.23570226039551587)),
 (4378, np.float64(0.23570226039551587)),
 (5353, np.float64(0.23570226039551587)),
 (5368, np.float64(0.23570226039551587)),
 (7280, np.float64(0.23570226039551587)),
 (7558, np.float64(0.23570226039551587)),
 (8111, np.float64(0.23570226039551587)),
 (9319, np.float64(0.23570226039551587)),
 (9887, np.float64(0.23570226039551587)),
 (8160, np.float64(0.2342606428329091)),
 (4135, np.float64(0.23211917272131483)),
 (9085, np.float64(0.23211917272131483)),
 (1650, np.float64(0.23145502494313785)),
 (2413, np.float64(0.23145502494313785)),
 (1635, np.float64(0.22941573387056174)),
 (2161, np.float64(0.22941573387056174)),
 (3625, np.float64(0.22941573387056174)),
 (4633, np.float64(0.22941573387056174)),
 (5434, np.float64(0.22941573387056174)),
 (6189, np.float64(0.22941573387056174)),
 (7570, np.float64(0.22941573387056174)),
 (95, np.float64(0.22613350843332272)),
 (1680, np.float64(0.22613350843332272)),
 (2036, np.float64(0.22613350843332272)),
 (4028, np.float64(0.22613350843332272)),
 (5558, np.float64(0.22613350843332272)),
 (8542, np.float64(0.22613350843332272)),
 (4942, np.float64(0.22450662753346864)),
 (6789, np.float64(0.22450662753346864)),
 (104, np.float64(0.22360679774997896)),
 (1614, np.float64(0.22360679774997896)),
 (2130, np.float64(0.22360679774997896)),
 (3712, np.float64(0.22360679774997896)),
 (5830, np.float64(0.22360679774997896)),
 (7809, np.float64(0.22360679774997896)),
 (8205, np.float64(0.22116293423234573)),
 (375, np.float64(0.22097086912079608)),
 (5903, np.float64(0.22097086912079608)),
 (9360, np.float64(0.22097086912079608)),
 (2446, np.float64(0.21879748724684184)),
 (1114, np.float64(0.2182178902359924)),
 (1619, np.float64(0.2182178902359924)),
 (1741, np.float64(0.2182178902359924)),
 (7269, np.float64(0.2182178902359924)),
 (8313, np.float64(0.2182178902359924)),
 (68, np.float64(0.2165063509461097)),
 (1473, np.float64(0.2165063509461097)),
 (1978, np.float64(0.2165063509461097)),
 (2293, np.float64(0.2165063509461097)),
 (2878, np.float64(0.2165063509461097)),
 (3108, np.float64(0.2165063509461097)),
 (3613, np.float64(0.2165063509461097)),
 (3627, np.float64(0.2165063509461097)),
 (3734, np.float64(0.2165063509461097)),
 (3780, np.float64(0.2165063509461097)),
 (4680, np.float64(0.2165063509461097)),
 (5027, np.float64(0.2165063509461097)),
 (5352, np.float64(0.2165063509461097)),
 (6156, np.float64(0.2165063509461097)),
 (6279, np.float64(0.2165063509461097)),
 (6574, np.float64(0.2165063509461097)),
 (6578, np.float64(0.2165063509461097)),
 (7121, np.float64(0.2165063509461097)),
 (7608, np.float64(0.2165063509461097)),
 (9145, np.float64(0.2165063509461097)),
 (9147, np.float64(0.2165063509461097)),
 (9307, np.float64(0.2165063509461097)),
 (593, np.float64(0.21437323142813602)),
 (1910, np.float64(0.21437323142813602)),
 (2040, np.float64(0.21437323142813602)),
 (5375, np.float64(0.21437323142813602)),
 (8263, np.float64(0.21437323142813602)),
 (513, np.float64(0.21320071635561041)),
 (1564, np.float64(0.21320071635561041)),
 (1625, np.float64(0.21320071635561041)),
 (4523, np.float64(0.21320071635561041)),
 (4767, np.float64(0.21320071635561041)),
 (5794, np.float64(0.21320071635561041)),
 (6742, np.float64(0.21320071635561041)),
 (8935, np.float64(0.21320071635561041)),
 (5718, np.float64(0.2091650066335189)),
 (3876, np.float64(0.20851441405707477)),
 (8725, np.float64(0.20851441405707477)),
 (8736, np.float64(0.20851441405707477)),
 (8893, np.float64(0.20851441405707477)),
 (9852, np.float64(0.20833333333333331)),
 (78, np.float64(0.20801257358446093)),
 (97, np.float64(0.20801257358446093)),
 (772, np.float64(0.20801257358446093)),
 (1056, np.float64(0.20801257358446093)),
 (1182, np.float64(0.20801257358446093)),
 (1254, np.float64(0.20801257358446093)),
 (1342, np.float64(0.20801257358446093)),
 (1596, np.float64(0.20801257358446093)),
 (1697, np.float64(0.20801257358446093)),
 (1924, np.float64(0.20801257358446093)),
 (2053, np.float64(0.20801257358446093)),
 (2833, np.float64(0.20801257358446093)),
 (2846, np.float64(0.20801257358446093)),
 (3148, np.float64(0.20801257358446093)),
 (3436, np.float64(0.20801257358446093)),
 (3594, np.float64(0.20801257358446093)),
 (3928, np.float64(0.20801257358446093)),
 (5763, np.float64(0.20801257358446093)),
 (6493, np.float64(0.20801257358446093)),
 (7716, np.float64(0.20801257358446093)),
 (8537, np.float64(0.20801257358446093)),
 (313, np.float64(0.20549873413169661)),
 (4535, np.float64(0.20412414523193154)),
 (1275, np.float64(0.20277677641345318)),
 (7076, np.float64(0.20277677641345318)),
 (792, np.float64(0.2004459314343183)),
 (1052, np.float64(0.2004459314343183)),
 (1126, np.float64(0.2004459314343183)),
 (1939, np.float64(0.2004459314343183)),
 (2431, np.float64(0.2004459314343183)),
 (3540, np.float64(0.2004459314343183)),
 (4227, np.float64(0.2004459314343183)),
 (5083, np.float64(0.2004459314343183)),
 (5168, np.float64(0.2004459314343183)),
 (5218, np.float64(0.2004459314343183)),
 (5768, np.float64(0.2004459314343183)),
 (6467, np.float64(0.2004459314343183)),
 (6572, np.float64(0.2004459314343183)),
 (6634, np.float64(0.2004459314343183)),
 (7847, np.float64(0.2004459314343183)),
 (8515, np.float64(0.2004459314343183)),
 (8809, np.float64(0.2004459314343183)),
 (9257, np.float64(0.2004459314343183)),
 (927, np.float64(0.20016019225635892)),
 (1551, np.float64(0.20016019225635892)),
 (3807, np.float64(0.20016019225635892)),
 (1919, np.float64(0.2001601922563589)),
 (798, np.float64(0.2)),
 (2308, np.float64(0.2)),
 (2492, np.float64(0.2)),
 (4376, np.float64(0.2)),
 (6610, np.float64(0.2)),
 (2919, np.float64(0.19764235376052372)),
 (1829, np.float64(0.19695964928958382)),
 (4441, np.float64(0.19695964928958382)),
 (40, np.float64(0.19611613513818404)),
 (810, np.float64(0.19611613513818404)),
 (6230, np.float64(0.19611613513818404)),
 (7098, np.float64(0.19611613513818404)),
 (3067, np.float64(0.1952172023607576)),
 (3249, np.float64(0.1952172023607576)),
 (399, np.float64(0.19521720236075757)),
 (1922, np.float64(0.19521720236075757)),
 (130, np.float64(0.19364916731037082)),
 (373, np.float64(0.19364916731037082)),
 (886, np.float64(0.19364916731037082)),
 (1174, np.float64(0.19364916731037082)),
 (1407, np.float64(0.19364916731037082)),
 (1547, np.float64(0.19364916731037082)),
 (1900, np.float64(0.19364916731037082)),
 (2120, np.float64(0.19364916731037082)),
 (2924, np.float64(0.19364916731037082)),
 (3003, np.float64(0.19364916731037082)),
 (3069, np.float64(0.19364916731037082)),
 (3083, np.float64(0.19364916731037082)),
 (3837, np.float64(0.19364916731037082)),
 (5262, np.float64(0.19364916731037082)),
 (5339, np.float64(0.19364916731037082)),
 (9081, np.float64(0.19364916731037082)),
 (355, np.float64(0.1928791874526149)),
 (3542, np.float64(0.1928791874526149)),
 (7245, np.float64(0.1928791874526149)),
 (7322, np.float64(0.19245008972987526)),
 (8108, np.float64(0.19205531989934396)),
 (689, np.float64(0.1889822365046136)),
 (1676, np.float64(0.1889822365046136)),
 (2782, np.float64(0.1889822365046136)),
 (3241, np.float64(0.1889822365046136)),
 (3268, np.float64(0.1889822365046136)),
 (6919, np.float64(0.1889822365046136)),
 (7737, np.float64(0.1889822365046136)),
 (9266, np.float64(0.1889822365046136)),
 (9882, np.float64(0.1889822365046136)),
 (8603, np.float64(0.18844459036110228)),
 (416, np.float64(0.1875)),
 (1202, np.float64(0.1875)),
 (1398, np.float64(0.1875)),
 (1974, np.float64(0.1875)),
 (2332, np.float64(0.1875)),
 (2476, np.float64(0.1875)),
 (2502, np.float64(0.1875)),
 (2761, np.float64(0.1875)),
 (2902, np.float64(0.1875)),
 (4831, np.float64(0.1875)),
 (4932, np.float64(0.1875)),
 (5141, np.float64(0.1875)),
 (8674, np.float64(0.1875)),
 (9449, np.float64(0.1875)),
 (9903, np.float64(0.1875)),
 (238, np.float64(0.1863389981249825)),
 (600, np.float64(0.18569533817705186)),
 (3006, np.float64(0.18569533817705186)),
 (7395, np.float64(0.18569533817705186)),
 (468, np.float64(0.18463723646899907)),
 (8563, np.float64(0.18257418583505536)),
 (187, np.float64(0.18190171877724973)),
 (384, np.float64(0.18190171877724973)),
 (653, np.float64(0.18190171877724973)),
 (800, np.float64(0.18190171877724973)),
 (827, np.float64(0.18190171877724973)),
 (1094, np.float64(0.18190171877724973)),
 (1378, np.float64(0.18190171877724973)),
 (1581, np.float64(0.18190171877724973)),
 (2081, np.float64(0.18190171877724973)),
 (2760, np.float64(0.18190171877724973)),
 (2939, np.float64(0.18190171877724973)),
 (4385, np.float64(0.18190171877724973)),
 (5606, np.float64(0.18190171877724973)),
 (6012, np.float64(0.18190171877724973)),
 (6149, np.float64(0.18190171877724973)),
 (6458, np.float64(0.18190171877724973)),
 (7265, np.float64(0.18190171877724973)),
 (7289, np.float64(0.18190171877724973)),
 (7866, np.float64(0.18190171877724973)),
 (8938, np.float64(0.18190171877724973)),
 (9026, np.float64(0.18190171877724973)),
 (621, np.float64(0.1805787796286538)),
 (225, np.float64(0.1796053020267749)),
 (1185, np.float64(0.1796053020267749)),
 (2416, np.float64(0.1796053020267749)),
 (4450, np.float64(0.1796053020267749)),
 (6700, np.float64(0.1796053020267749)),
 (481, np.float64(0.17801724872907798)),
 (253, np.float64(0.1767766952966369)),
 (467, np.float64(0.1767766952966369)),
 (520, np.float64(0.1767766952966369)),
 (666, np.float64(0.1767766952966369)),
 (733, np.float64(0.1767766952966369)),
 (1355, np.float64(0.1767766952966369)),
 (1578, np.float64(0.1767766952966369)),
 (1875, np.float64(0.1767766952966369)),
 (2103, np.float64(0.1767766952966369)),
 (2192, np.float64(0.1767766952966369)),
 (2313, np.float64(0.1767766952966369)),
 (2822, np.float64(0.1767766952966369)),
 (3164, np.float64(0.1767766952966369)),
 (3943, np.float64(0.1767766952966369)),
 (4629, np.float64(0.1767766952966369)),
 (5519, np.float64(0.1767766952966369)),
 (6021, np.float64(0.1767766952966369)),
 (7318, np.float64(0.1767766952966369)),
 (8773, np.float64(0.1767766952966369)),
 (8894, np.float64(0.1767766952966369)),
 (9772, np.float64(0.1767766952966369)),
 (447, np.float64(0.17677669529663687)),
 (540, np.float64(0.17677669529663687)),
 (1507, np.float64(0.17677669529663687)),
 (2262, np.float64(0.17677669529663687)),
 (2670, np.float64(0.17677669529663687)),
 (2819, np.float64(0.17677669529663687)),
 (3216, np.float64(0.17677669529663687)),
 (3341, np.float64(0.17677669529663687)),
 (5091, np.float64(0.17677669529663687)),
 (5318, np.float64(0.17677669529663687)),
 (5366, np.float64(0.17677669529663687)),
 (6241, np.float64(0.17677669529663687)),
 (6698, np.float64(0.17677669529663687)),
 (8596, np.float64(0.17677669529663687)),
 (9284, np.float64(0.17677669529663687)),
 (9382, np.float64(0.17677669529663687)),
 (2662, np.float64(0.17407765595569785)),
 (4285, np.float64(0.17407765595569785)),
 (6892, np.float64(0.17407765595569785)),
 (8637, np.float64(0.17334381132038412)),
 (219, np.float64(0.1720618004029213)),
 (471, np.float64(0.1720618004029213)),
 (551, np.float64(0.1720618004029213)),
 (607, np.float64(0.1720618004029213)),
 (1085, np.float64(0.1720618004029213)),
 (1610, np.float64(0.1720618004029213)),
 (1688, np.float64(0.1720618004029213)),
 (1770, np.float64(0.1720618004029213)),
 (1818, np.float64(0.1720618004029213)),
 (2209, np.float64(0.1720618004029213)),
 (2636, np.float64(0.1720618004029213)),
 (2988, np.float64(0.1720618004029213)),
 (3353, np.float64(0.1720618004029213)),
 (4551, np.float64(0.1720618004029213)),
 (4912, np.float64(0.1720618004029213)),
 (5130, np.float64(0.1720618004029213)),
 (5902, np.float64(0.1720618004029213)),
 (6007, np.float64(0.1720618004029213)),
 (6137, np.float64(0.1720618004029213)),
 (7223, np.float64(0.1720618004029213)),
 (7593, np.float64(0.1720618004029213)),
 (7692, np.float64(0.1720618004029213)),
 (9101, np.float64(0.1720618004029213)),
 (4234, np.float64(0.17149858514250882)),
 (7470, np.float64(0.17149858514250882)),
 (8303, np.float64(0.17149858514250882)),
 (168, np.float64(0.1690308509457033)),
 (4173, np.float64(0.1690308509457033)),
 (8277, np.float64(0.16854996561581054)),
 (579, np.float64(0.16770509831248423)),
 (675, np.float64(0.16770509831248423)),
 (1514, np.float64(0.16770509831248423)),
 (1529, np.float64(0.16770509831248423)),
 (1595, np.float64(0.16770509831248423)),
 (3621, np.float64(0.16770509831248423)),
 (4092, np.float64(0.16770509831248423)),
 (4327, np.float64(0.16770509831248423)),
 (4387, np.float64(0.16770509831248423)),
 (4540, np.float64(0.16770509831248423)),
 (5152, np.float64(0.16770509831248423)),
 (5705, np.float64(0.16770509831248423)),
 (6073, np.float64(0.16770509831248423)),
 (6960, np.float64(0.16770509831248423)),
 (7034, np.float64(0.16770509831248423)),
 (7903, np.float64(0.16770509831248423)),
 (8213, np.float64(0.16770509831248423)),
 (9238, np.float64(0.16770509831248423)),
 (410, np.float64(0.16666666666666666)),
 (444, np.float64(0.16666666666666666)),
 (490, np.float64(0.16666666666666666)),
 (841, np.float64(0.16666666666666666)),
 (2829, np.float64(0.16666666666666666)),
 (2938, np.float64(0.16666666666666666)),
 (4012, np.float64(0.16666666666666666)),
 (4792, np.float64(0.16666666666666666)),
 (6393, np.float64(0.16666666666666666)),
 (7024, np.float64(0.16666666666666666)),
 (7030, np.float64(0.16666666666666666)),
 (7110, np.float64(0.16666666666666666)),
 (7472, np.float64(0.16666666666666666)),
 (8407, np.float64(0.16666666666666666)),
 (9192, np.float64(0.16666666666666666)),
 (4318, np.float64(0.16610264925668733)),
 (6237, np.float64(0.16556654463313047)),
 (622, np.float64(0.1643989873053573)),
 (2215, np.float64(0.1643989873053573)),
 (6804, np.float64(0.1643989873053573)),
 (7891, np.float64(0.1643989873053573)),
 (2707, np.float64(0.16413304107465318)),
 (735, np.float64(0.1636634176769943)),
 (819, np.float64(0.1636634176769943)),
 (859, np.float64(0.1636634176769943)),
 (884, np.float64(0.1636634176769943)),
 (924, np.float64(0.1636634176769943)),
 (3187, np.float64(0.1636634176769943)),
 (3372, np.float64(0.1636634176769943)),
 (3937, np.float64(0.1636634176769943)),
 (4157, np.float64(0.1636634176769943)),
 (4250, np.float64(0.1636634176769943)),
 (4892, np.float64(0.1636634176769943)),
 (5074, np.float64(0.1636634176769943)),
 (5257, np.float64(0.1636634176769943)),
 (5457, np.float64(0.1636634176769943)),
 (5684, np.float64(0.1636634176769943)),
 (5728, np.float64(0.1636634176769943)),
 (7064, np.float64(0.1636634176769943)),
 (7323, np.float64(0.1636634176769943)),
 (8177, np.float64(0.1636634176769943)),
 (8684, np.float64(0.1636634176769943)),
 (9062, np.float64(0.1636634176769943)),
 (9503, np.float64(0.1636634176769943)),
 (9507, np.float64(0.1636634176769943)),
 (9998, np.float64(0.1636634176769943)),
 (818, np.float64(0.16222142113076254)),
 (1734, np.float64(0.16222142113076254)),
 (965, np.float64(0.16137430609197567)),
 (6479, np.float64(0.16012815380508713)),
 (8324, np.float64(0.16012815380508713)),
 (242, np.float64(0.1599005372667078)),
 (649, np.float64(0.1599005372667078)),
 (1575, np.float64(0.1599005372667078)),
 (1611, np.float64(0.1599005372667078)),
 (2230, np.float64(0.1599005372667078)),
 (4511, np.float64(0.1599005372667078)),
 (4659, np.float64(0.1599005372667078)),
 (5092, np.float64(0.1599005372667078)),
 (8053, np.float64(0.1599005372667078)),
 (8393, np.float64(0.1599005372667078)),
 (4413, np.float64(0.15875015875023812)),
 (217, np.float64(0.15811388300841897)),
 (241, np.float64(0.15811388300841897)),
 (725, np.float64(0.15811388300841897)),
 (760, np.float64(0.15811388300841897)),
 (1307, np.float64(0.15811388300841897)),
 (1447, np.float64(0.15811388300841897)),
 (1813, np.float64(0.15811388300841897)),
 (2095, np.float64(0.15811388300841897)),
 (2732, np.float64(0.15811388300841897)),
 (2783, np.float64(0.15811388300841897)),
 (3005, np.float64(0.15811388300841897)),
 (3474, np.float64(0.15811388300841897)),
 (3576, np.float64(0.15811388300841897)),
 (3649, np.float64(0.15811388300841897)),
 (4480, np.float64(0.15811388300841897)),
 (4872, np.float64(0.15811388300841897)),
 (5075, np.float64(0.15811388300841897)),
 (5329, np.float64(0.15811388300841897)),
 (6484, np.float64(0.15811388300841897)),
 (7335, np.float64(0.15811388300841897)),
 (7340, np.float64(0.15811388300841897)),
 (7438, np.float64(0.15811388300841897)),
 (7525, np.float64(0.15811388300841897)),
 (7691, np.float64(0.15811388300841897)),
 (7966, np.float64(0.15811388300841897)),
 (8439, np.float64(0.15811388300841897)),
 (8476, np.float64(0.15811388300841897)),
 (9309, np.float64(0.15811388300841897)),
 (9504, np.float64(0.15811388300841897)),
 (9685, np.float64(0.15811388300841897)),
 (9765, np.float64(0.15811388300841897)),
 (237, np.float64(0.1563858105428061)),
 (585, np.float64(0.1563858105428061)),
 (960, np.float64(0.1563858105428061)),
 (1105, np.float64(0.1563858105428061)),
 (1334, np.float64(0.1563858105428061)),
 (1677, np.float64(0.1563858105428061)),
 (2340, np.float64(0.1563858105428061)),
 (2394, np.float64(0.1563858105428061)),
 (2858, np.float64(0.1563858105428061)),
 (2877, np.float64(0.1563858105428061)),
 (5011, np.float64(0.1563858105428061)),
 (5023, np.float64(0.1563858105428061)),
 (5571, np.float64(0.1563858105428061)),
 (5631, np.float64(0.1563858105428061)),
 (5664, np.float64(0.1563858105428061)),
 (6297, np.float64(0.1563858105428061)),
 (8037, np.float64(0.1563858105428061)),

In [17]:
def recommand(movies):
    index=movies1[movies1['title']==movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse=True, key=lambda vector:vector[1])
    for i in distance[0:5]:
        print(movies1.iloc[i[0]].title)

In [18]:
recommand("Benny & Joon")

Benny & Joon
Playing It Cool
Rab Ne Bana Di Jodi
The Quiet Man
Everything Is Illuminated

In [19]:
import pickle

In [20]:
pickle.dump(movies1, open('movies_list.pkl', 'wb'))

In [21]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))

In [22]:
pickle.load(open('movies_list.pkl', 'rb'))

,id,title,original_language,popularity,release_date,vote_average,vote_count,tag
0,278,The Shawshank Redemption,en,94.075,1994-09-23,8.7,21862,Framed in the 1940s for the double murder of h...
1,19404,Dilwale Dulhania Le Jayenge,hi,25.408,1995-10-19,8.7,3731,"Raj is a rich, carefree, happy-go-lucky second..."
2,238,The Godfather,en,90.585,1972-03-14,8.7,16280,"Spanning the years 1945 to 1955, a chronicle o..."
3,424,Schindler's List,en,44.761,1993-12-15,8.6,12959,The true story of how businessman Oskar Schind...
4,240,The Godfather: Part II,en,57.749,1974-12-20,8.6,9811,In the continuing saga of the Corleone crime f...
...,...,...,...,...,...,...,...,...
9995,10196,The Last Airbender,en,98.322,2010-06-30,4.7,3347,"The story follows the adventures of Aang, a yo..."
9996,331446,Sharknado 3: Oh Hell No!,en,12.490,2015-07-22,4.7,417,The sharks take bite out of the East Coast whe...
9997,13995,Captain America,en,18.333,1990-12-14,4.6,332,"During World War II, a brave, patriotic Americ..."
9998,2312,In the Name of the King: A Dungeon Siege Tale,en,15.159,2007-11-29,4.7,668,A man named Farmer sets out to rescue his kidn...
9999,455957,Domino,en,16.482,2019-05-31,4.6,221,Seeking justice for his partner’s murder by an...